FROM ubuntu:24.04

RUN apt update && apt install -y \
    mingw-w64 \
    cmake \
    make \
    git \
    wget \
    pkg-config \
    unzip \
    python3   \
    python3-pip

RUN echo "\
set(CMAKE_SYSTEM_NAME Windows)\n\
set(CMAKE_SYSTEM_PROCESSOR x86_64)\n\
set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)\n\
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)\n\
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)\n\
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)\n\
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)\n\
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)\n\
set(CMAKE_INSTALL_PREFIX /usr/x86_64-w64-mingw32)\n\
" > /mingw-toolchain.cmake

ENV TOOLCHAIN_FILE=/mingw-toolchain.cmake
ENV PREFIX=/usr/x86_64-w64-mingw32

EXPOSE 7777